/**
 * GraphQL Code Generator Configuration
 *
 * Generates typed GraphQL operations from the documents in src/ against the
 * live dev schema. Output is committed, so builds and CI never need a
 * running backend — only `npm run codegen` does.
 *
 * Usage:
 *   cd backend && npm run dev     # introspection is on when NODE_ENV != production
 *   cd web/app && npm run codegen
 */
import { basename } from 'node:path';
import type { CodegenConfig } from '@graphql-codegen/cli';

// The client preset writes four files and has no header option, so the
// beforeOneFileWrite hook below prepends these on every run.
const HEADERS: Record<string, string> = {
  'graphql.ts': `/**
 * Generated GraphQL Types
 *
 * Operation types and document nodes for every query and mutation in src/.
 * Generated by \`npm run codegen\` — do not edit by hand.
 */`,
  'gql.ts': `/**
 * Generated GraphQL Document Map
 *
 * Maps each operation string to its typed document node, backing the
 * \`graphql()\` helper components call.
 * Generated by \`npm run codegen\` — do not edit by hand.
 */`,
  'fragment-masking.ts': `/**
 * Generated Fragment Masking Helpers
 *
 * FragmentType, useFragment, makeFragmentData, and isFragmentReady — the
 * utilities that unmask fragment data at the point of use.
 * Generated by \`npm run codegen\` — do not edit by hand.
 */`,
  'index.ts': `/**
 * Generated GraphQL Barrel
 *
 * Public export surface for the generated GraphQL helpers.
 * Generated by \`npm run codegen\` — do not edit by hand.
 */`,
};

const config: CodegenConfig = {
  // Runs in Node, so this reads process.env — the app itself reads the same
  // variable through import.meta.env.
  schema: process.env.VITE_API_URL ?? 'http://localhost:4000/graphql',
  documents: ['src/**/*.{ts,tsx}', '!src/gql/**/*'],
  ignoreNoDocuments: true,
  // The DateTime scalar serializes to an ISO string over the wire.
  config: { scalars: { DateTime: 'string' } },
  generates: {
    // Default client-preset output is TypedDocumentNode, which is what
    // Apollo's useQuery expects.
    './src/gql/': {
      preset: 'client',
    },
  },
  hooks: {
    beforeOneFileWrite: (filePath: string, content: string) => {
      const header = HEADERS[basename(filePath)];
      return header ? `${header}\n${content}` : content;
    },
  },
};

export default config;
