/**
 * ESLint Configuration
 *
 * Flat config for the volunteer web client. CI calls the ESLint CLI
 * directly via `npm run lint`.
 *
 * Ignores:
 *   - dist/, .next/: build output, the latter left over from the Next.js build
 *   - src/gql/: graphql-codegen output, regenerated by `npm run codegen`
 */
import js from '@eslint/js';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: ['dist/**', '.next/**', 'node_modules/**', 'src/gql/**'],
  },
  {
    files: ['src/**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommended,
      reactHooks.configs.flat['recommended-latest'],
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    rules: {
      // A leading underscore marks a parameter kept only to reach the ones
      // after it — common in callback signatures.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // Root-level config files run in Node, not the browser.
    files: ['*.ts', '*.mjs'],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.node,
    },
  }
);
