/**
 * ESLint Configuration
 *
 * Flat config for the volunteer web client. Next 16 removed `next lint`,
 * so CI calls the ESLint CLI directly via `npm run lint`.
 *
 * Ignores:
 *   - src/gql/: graphql-codegen output, regenerated by `npm run codegen`
 */
import coreWebVitals from 'eslint-config-next/core-web-vitals';
import typescript from 'eslint-config-next/typescript';

const eslintConfig = [
  {
    ignores: ['.next/**', 'node_modules/**', 'src/gql/**', 'next-env.d.ts'],
  },
  ...coreWebVitals,
  ...typescript,
];

export default eslintConfig;
